# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
universal_binaries:
  - id: envd
    replace: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd
    main: ./cmd/envd
    binary: envd
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd/pkg/version.gitTreeState=clean
      - -X github.com/tensorchord/envd/pkg/version.gitTag={{ .Tag }}
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd-sshd
    main: ./cmd/envd-sshd
    binary: envd-sshd
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd/pkg/version.gitTreeState=clean
archives:
  - id: envd
    format: binary
    builds:
      - envd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - id: envd-sshd
    format: binary
    builds:
      - envd-sshd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  groups:
    - title: 'Exciting New Features 🎉'
      regexp: "^.*feat.*"
      order: 0
    - title: 'Bug Fix 🛠'
      regexp: "^.*(Fix|fix|bug).*"
      order: 1
    - title: 'Refactor 🏗️'
      regexp: "^.*refact.*"
      order: 2
    - title: 'Documentation 🖊️'
      regexp: "^.*docs.*"
      order: 3
    - title: 'Others:'
      order: 999
