name: release

on:
  push:
    tags:
      - '*'
  pull_request:
    paths:
    - '.github/workflows/release.yml'
    - '.goreleaser/'
    - '.goreleaser.yaml'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}      
      - name: upload gobin
        uses: actions/upload-artifact@v3
        with:
          name: gobin_${{ github.event.release.tag_name }}
          retention-days: 1
          path: |
            dist/envd_${{ github.event.release.tag_name }}_Linux_x86_64
            dist/envd-ssh${{ github.event.release.tag_name }}_Linux_x86_64
          if-no-files-found: error
  pypi_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get gobin
      uses: actions/download-artifact@v3
      with:
        name: gobin_${{ github.event.release.tag_name }}
        path: bin/
    - name: Build wheel
      with:
        python-version: "3.9"
      run: |      
          ls bin/
          python -m pip install --upgrade pip
          python -m pip install twine wheel auditwheel
          python setup.py bdist_wheel
          auditwheel repair dist/*
          ls .
          ls dist/
          ls wheelhouse/



